name: app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.2
  copy_with_extension_gen: ^5.0.2
  equatable: ^2.0.5
  intl: ^0.19.0
  flutter_bloc: ^8.1.4
  flutter_localization: ^0.2.0
  cached_network_image: ^3.2.3
  connectivity_plus: ^6.0.5
  flutter_staggered_animations: ^1.1.1
  loading_animation_widget: ^1.2.1
  page_transition: ^2.1.0
  video_player: ^2.8.3
  flick_video_player: ^0.9.0
  http: ^1.2.0
  translator: ^1.0.0
  fluttertoast: ^8.2.4
  card_swiper: ^3.0.1
  go_router: ^14.2.8
  hive: ^2.2.3
  path_provider: ^2.1.2
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  firebase_messaging: ^15.1.2
  firebase_analytics: ^11.3.2
  firebase_core: ^3.5.0
  permission_handler: ^11.3.1
  flutter_cache_manager: ^3.3.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.6.2
  build_runner: ^2.3.3

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
